name: autotiler
channels:
  - conda-forge
dependencies:
  - python=3.7
  - dask
  - numpy
  - matplotlib
  - pandas
  - panel
  - pip
  - rasterio
  - streamlit
  - terracotta
  - xarray
  - pip:
    - rio-hist
